version: '3.8'
services:
  app:
    container_name: nxlog-test-app
    build: .
    volumes:
      - .:/nxlog-test
      - /nxlog-test/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start